import 'dart:io';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:url_launcher/url_launcher.dart';

import '../../state/providers/auth_provider.dart';

class AdminSettingsScreen extends ConsumerStatefulWidget {
  const AdminSettingsScreen({super.key});

  @override
  ConsumerState<AdminSettingsScreen> createState() =>
      _AdminSettingsScreenState();
}

class _AdminSettingsScreenState extends ConsumerState<AdminSettingsScreen> {
  final _auth = FirebaseAuth.instance;
  final _firestore = FirebaseFirestore.instance;

  bool _isDark = false;
  bool _uploadingPhoto = false;

  User get _user => _auth.currentUser!;

  Future<DocumentSnapshot<Map<String, dynamic>>> _userDoc() {
    return _firestore.collection('users').doc(_user.uid).get();
  }

  Future<void> _changeDisplayName() async {
    final doc = await _userDoc();
    final currentName = (doc.data()?['name'] ?? _user.displayName ?? '')
        .toString();

    final controller = TextEditingController(text: currentName);

    if (!mounted) return;
    await showDialog(
      context: context,
      builder: (_) => AlertDialog(
        title: const Text('Change Display Name'),
        content: TextField(
          controller: controller,
          decoration: const InputDecoration(
            labelText: 'New name',
            border: OutlineInputBorder(),
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () async {
              final newName = controller.text.trim();
              if (newName.isEmpty) return;

              await _user.updateDisplayName(newName);

              await _firestore.collection('users').doc(_user.uid).set({
                'name': newName,
              }, SetOptions(merge: true));

              ref.invalidate(currentUserProvider);

              if (!mounted) return;
              Navigator.pop(context);
              ScaffoldMessenger.of(context).showSnackBar(
                const SnackBar(content: Text('Name updated successfully')),
              );
              setState(() {});
            },
            child: const Text('Save'),
          ),
        ],
      ),
    );
  }

  Future<void> _resetPassword() async {
    await _auth.sendPasswordResetEmail(email: _user.email!);
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Password reset email sent. Check your inbox.'),
      ),
    );
  }

  Future<void> _exportAdminReport() async {
    final pdf = pw.Document();

    final firestore = FirebaseFirestore.instance;

    final rescuerCount =
        (await firestore
                .collection('users')
                .where('role', isEqualTo: 'rescuer')
                .get())
            .docs
            .length;

    final injuryCount =
        (await firestore.collection('injuries').get()).docs.length;

    final userDoc = await firestore.collection('users').doc(_user.uid).get();
    final adminName = (userDoc.data()?['name'] ?? _user.displayName ?? 'N/A')
        .toString();

    final reportData = {
      'Admin Name': adminName,
      'Email': _user.email ?? 'N/A',
      'Total Rescuers': rescuerCount.toString(),
      'Total Injuries Logged': injuryCount.toString(),
      'Generated': DateFormat.yMMMMd().format(DateTime.now()),
    };

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Padding(
          padding: const pw.EdgeInsets.all(32),
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Mountain Rescue - Admin Report',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue900,
                ),
              ),
              pw.SizedBox(height: 16),
              pw.Text('Generated by: ${_user.email}'),
              pw.Divider(),
              pw.SizedBox(height: 20),
              ...reportData.entries.map(
                (e) => pw.Padding(
                  padding: const pw.EdgeInsets.symmetric(vertical: 6),
                  child: pw.Text(
                    '${e.key}: ${e.value}',
                    style: const pw.TextStyle(fontSize: 16),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );

    await Printing.layoutPdf(onLayout: (format) => pdf.save());
  }

  Future<void> _contactSupport() async {
    final userDoc = await _userDoc();
    final adminName = (userDoc.data()?['name'] ?? _user.displayName ?? 'Admin')
        .toString();

    final uri = Uri(
      scheme: 'mailto',
      path: 'support@mountainrescue.app',
      queryParameters: {
        'subject': 'Admin Support Request',
        'body':
            'Hello,\n\nI need help with the Mountain Rescue admin panel.\n\nBest regards,\n$adminName',
      },
    );

    if (await canLaunchUrl(uri)) {
      await launchUrl(uri);
    } else {
      if (!mounted) return;
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Could not open email app.')),
      );
    }
  }

  Future<void> _pickAndUploadProfilePhoto() async {
    if (_uploadingPhoto) return;

    final picker = ImagePicker();

    if (!mounted) return;
    final source = await showModalBottomSheet<ImageSource>(
      context: context,
      shape: const RoundedRectangleBorder(
        borderRadius: BorderRadius.vertical(top: Radius.circular(18)),
      ),
      builder: (_) => SafeArea(
        child: Wrap(
          children: [
            ListTile(
              leading: const Icon(Icons.photo_library),
              title: const Text('Choose from Gallery'),
              onTap: () => Navigator.pop(context, ImageSource.gallery),
            ),
            ListTile(
              leading: const Icon(Icons.photo_camera),
              title: const Text('Take Photo'),
              onTap: () => Navigator.pop(context, ImageSource.camera),
            ),
            ListTile(
              leading: const Icon(Icons.close),
              title: const Text('Cancel'),
              onTap: () => Navigator.pop(context, null),
            ),
          ],
        ),
      ),
    );

    if (source == null) return;

    final picked = await picker.pickImage(
      source: source,
      imageQuality: 85,
      maxWidth: 1024,
    );

    if (picked == null) return;

    setState(() => _uploadingPhoto = true);

    try {
      final file = File(picked.path);

      final refStorage = FirebaseStorage.instance
          .ref()
          .child('profile_pictures')
          .child('${_user.uid}.jpg');

      await refStorage.putFile(
        file,
        SettableMetadata(contentType: 'image/jpeg'),
      );

      final downloadUrl = await refStorage.getDownloadURL();

      await _user.updatePhotoURL(downloadUrl);

      await _firestore.collection('users').doc(_user.uid).set({
        'photoUrl': downloadUrl,
      }, SetOptions(merge: true));

      ref.invalidate(currentUserProvider);

      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(const SnackBar(content: Text('Profile photo updated')));

      setState(() {});
    } catch (e) {
      if (!mounted) return;
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text('Failed to update photo: $e')));
    } finally {
      if (mounted) setState(() => _uploadingPhoto = false);
    }
  }

  void _logout() async {
    await ref.read(authRepositoryProvider).signOut();
    if (!mounted) return;
    Navigator.pop(context);
  }

  @override
  Widget build(BuildContext context) {
    _isDark = Theme.of(context).brightness == Brightness.dark;

    return FutureBuilder(
      future: _userDoc(),
      builder: (context, snapshot) {
        final data = snapshot.data?.data();
        final displayName = (data?['name'] ?? _user.displayName ?? 'Admin')
            .toString();

        final photoUrl = (data?['photoUrl'] ?? _user.photoURL)?.toString();

        return Scaffold(
          appBar: AppBar(
            title: const Text('Admin Settings'),
            backgroundColor: const Color(0xFF1565C0),
            foregroundColor: Colors.white,
          ),
          body: Container(
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: _isDark
                    ? [const Color(0xFF1A237E), const Color(0xFF0D47A1)]
                    : [const Color(0xFF1565C0), const Color(0xFF42A5F5)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
            ),
            child: SafeArea(
              child: ListView(
                padding: const EdgeInsets.all(24),
                children: [
                  Center(
                    child: Column(
                      children: [
                        Stack(
                          alignment: Alignment.bottomRight,
                          children: [
                            CircleAvatar(
                              radius: 48,
                              backgroundImage: photoUrl != null
                                  ? NetworkImage(photoUrl)
                                  : null,
                              backgroundColor: Colors.white,
                              child: photoUrl == null
                                  ? const Icon(
                                      Icons.admin_panel_settings,
                                      color: Color(0xFF1565C0),
                                      size: 48,
                                    )
                                  : null,
                            ),
                            Positioned(
                              bottom: 0,
                              right: 0,
                              child: InkWell(
                                onTap: _uploadingPhoto
                                    ? null
                                    : _pickAndUploadProfilePhoto,
                                borderRadius: BorderRadius.circular(18),
                                child: Container(
                                  padding: const EdgeInsets.all(8),
                                  decoration: BoxDecoration(
                                    color: Colors.white,
                                    borderRadius: BorderRadius.circular(18),
                                    boxShadow: [
                                      BoxShadow(
                                        color: Colors.black.withValues(
                                          alpha: 0.15,
                                        ),
                                        blurRadius: 8,
                                        offset: const Offset(0, 2),
                                      ),
                                    ],
                                  ),
                                  child: _uploadingPhoto
                                      ? const SizedBox(
                                          width: 18,
                                          height: 18,
                                          child: CircularProgressIndicator(
                                            strokeWidth: 2,
                                          ),
                                        )
                                      : const Icon(
                                          Icons.camera_alt,
                                          size: 18,
                                          color: Color(0xFF1565C0),
                                        ),
                                ),
                              ),
                            ),
                          ],
                        ),
                        const SizedBox(height: 12),
                        Text(
                          displayName,
                          style: const TextStyle(
                            color: Colors.white,
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                          ),
                        ),
                        Text(
                          _user.email ?? '',
                          style: TextStyle(
                            color: Colors.white.withValues(alpha: 0.9),
                            fontSize: 14,
                          ),
                        ),
                        const SizedBox(height: 20),
                        ElevatedButton.icon(
                          onPressed: _changeDisplayName,
                          icon: const Icon(Icons.edit),
                          label: const Text('Edit Name'),
                          style: ElevatedButton.styleFrom(
                            backgroundColor: Colors.white.withValues(
                              alpha: 0.2,
                            ),
                            foregroundColor: Colors.white,
                          ),
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 30),

                  ListTile(
                    leading: const Icon(Icons.image, color: Colors.white),
                    title: const Text(
                      'Change Profile Picture',
                      style: TextStyle(color: Colors.white),
                    ),
                    subtitle: Text(
                      'Upload a new avatar photo',
                      style: TextStyle(
                        color: Colors.white.withValues(alpha: 0.8),
                      ),
                    ),
                    onTap: _uploadingPhoto ? null : _pickAndUploadProfilePhoto,
                  ),

                  ListTile(
                    leading: const Icon(
                      Icons.lock_outline,
                      color: Colors.white,
                    ),
                    title: const Text(
                      'Change Password',
                      style: TextStyle(color: Colors.white),
                    ),
                    onTap: _resetPassword,
                  ),
                  ListTile(
                    leading: const Icon(
                      Icons.picture_as_pdf,
                      color: Colors.white,
                    ),
                    title: const Text(
                      'Export System Report (PDF)',
                      style: TextStyle(color: Colors.white),
                    ),
                    onTap: _exportAdminReport,
                  ),
                  ListTile(
                    leading: const Icon(
                      Icons.email_outlined,
                      color: Colors.white,
                    ),
                    title: const Text(
                      'Contact Support',
                      style: TextStyle(color: Colors.white),
                    ),
                    onTap: _contactSupport,
                  ),
                  ListTile(
                    leading: const Icon(
                      Icons.info_outline,
                      color: Colors.white,
                    ),
                    title: const Text(
                      'About App',
                      style: TextStyle(color: Colors.white),
                    ),
                    onTap: () {
                      showAboutDialog(
                        context: context,
                        applicationName: 'Mountain Rescue - Admin Panel',
                        applicationVersion: '1.2.0',
                        applicationLegalese:
                            '© 2025 Mountain Rescue Team. All rights reserved.',
                      );
                    },
                  ),
                  const Divider(color: Colors.white54),
                  ListTile(
                    leading: const Icon(Icons.logout, color: Colors.redAccent),
                    title: const Text(
                      'Logout',
                      style: TextStyle(color: Colors.redAccent),
                    ),
                    onTap: _logout,
                  ),
                ],
              ),
            ),
          ),
        );
      },
    );
  }
}
